language: php

sudo: false

php:
  - 8.1

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-es
      - language-pack-fr

script:
  - composer install --prefer-dist --no-interaction --optimize-autoloader
  - vendor/bin/phpunit --configuration phpunit.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v
